analysis:
  classification:
    batch_size: 16
    max_length: 512
    model: distilbert-base-uncased
  ner:
    entities:
    - PERSON
    - ORG
    - GPE
    - LOC
    - DATE
    model: fr_core_news_md
  sentiment:
    model: transformers
    transformer_model: cmarkea/distilcamembert-base-sentiment
  topic_modeling:
    algorithm: lda
    clustering_method: kmeans
    max_df: 0.7
    min_df: 5
    n_clusters: 5
    num_topics: 6
    topic_range_min: 2
    topic_range_max: 50
    topic_range_step: 2
    coherence_improvement_threshold: 0.05  # 5% improvement threshold for elbow detection
    preprocessing:
      allowed_pos:
      - NOUN
      - PROPN
      - ADJ
      filter_ads: true
      min_token_length: 3
      spacy_model: fr_core_news_md
    use_spacy_preprocessing: true
    bertopic:
      # Paramètres UMAP pour la réduction de dimensionnalité
      umap_n_neighbors: 15
      umap_n_components: 5
      umap_min_dist: 0.0
      # Paramètres HDBSCAN pour le clustering (valeurs réduites pour moins d'outliers)
      hdbscan_min_cluster_size: 5  # Valeur par défaut réduite (15 → 5)
      hdbscan_min_samples: 3       # Valeur par défaut réduite (10 → 3)
      # Activation de la redistribution des outliers
      redistribute_outliers: true
      # Modèle d'embedding
      embedding_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      # Autres paramètres
      batch_size: 64
      use_pca: true
      pca_components: 50
data:
  cluster_results_dir: data/results/clusters/
  files:
    articles: classified_tv_programs_20250523_104843_filtered.json
  lexical_analysis_dir: data/results/lexical_analysis/
  processed_dir: C:\Users\nicol\Documents\Projects\newspapers-analysis\data\processed
  raw_dir: data/raw
  results_dir: data/results
llm:
  default_provider: openai
  mistral:
    api_key: feMLPgurZBqgTtUb2ENswldmMUZNBf53
    endpoint: https://api.mistral.ai/v1/chat/completions
    language: fr
    model: mistral-small
    provider: mistral
  openai:
    api_key: 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
    endpoint: https://api.openai.com/v1/chat/completions
    language: fr
    model: gpt-4o
    provider: openai
logging:
  level: INFO
  log_file: ../logs/newspaper_analysis.log
  log_to_file: true
mongodb:
  collection: press_processed
  database: articles
  password: xzSI4OZiwhPV3zrh
  uri: mongodb+srv://therori-mac:xzSI4OZiwhPV3zrh@articles.futmiee.mongodb.net/?retryWrites=true&w=majority&appName=articles
  username: therori-mac
preprocessing:
  language: english
  lemmatize: true
  min_doc_length: 50
  min_word_length: 3
  remove_stopwords: true
visualization:
  color_palette: viridis
  default_figsize:
  - 12
  - 8
  dpi: 300
  save_format: png
